### ISSUE TITLE
Bug in insertPlotlyReset with shinyjs 2.0.0

### ISSUE THREAD

**Issue by potockan** [lianos/multiGSEA.shiny#10]
Hi Steve,

With the newest `shinyjs` package there is an error in `insertPlotlyReset` function. The reason is missing argument `functions` in `shinyjs::extendShinyjs`. To fix that simply change [this line](https://github.com/lianos/multiGSEA.shiny/blob/develop/R/shiny-utils.R#L53) from `extendShinyjs(text=text)` to `extendShinyjs(text=text, functions=sprintf("reset_%s_%s", source, event))`.

The quick bug fix would be much appreciated.

Thanks,
Natalia

**Comment by lianos** [comment]
Done! Thanks for the bug report and fix, Natalia!

**Comment by potockan** [comment]
Great, thanks for the quick reaction!
