### ISSUE TITLE
dtplyr dependency is not listed in the DESCRIPTION

### ISSUE THREAD

**Issue by tomsing1** [lianos/multiGSEA.shiny#3]
I tried to use the `explore()` function, which complained that the `dtplyr` package wasn't available on my system. Perhaps that should be listed in the DESCRIPTION of the package somewhere, so it is installed by default?
https://github.com/lianos/multiGSEA.shiny/blob/4aed7bdc41554cfaa06852674313b56b944e27e9/inst/shiny/global.R#L10

(It is on the list of packages installed in the docker image for deployment.)

**Comment by lianos** [comment]
This is fixed by commit 043f22a, thanks!
