### ISSUE TITLE
Multiple results from the analysis

### ISSUE THREAD

**Issue by dktanwar** [lianos/multiGSEA.shiny#5]
Hi,

Thank you for a very nice tool!

I have a list of analysis done by `multiGSEA`:

- a_vs_b
- b_vs_c
- a_vs_c

How can I visualize them in the shiny app?

I would like to load them once, and then select them via **drop-down** menu.

**Comment by lianos** [comment]
Hi Deepak,

Thanks for your interest in this project. I understand your use case, however at this point in time, you'll have to settle for viewing each contrast independently by launching three instances of the `multiGSEA.shiny::explore()` app.

I can see the appeal in your suggestion, but I've got another app "up my sleeve" to enable interactive exploration of omics data that I hope will see the light of day ... that app leverages the building blocks provided by the `multiGSEA.shiny` package.
